### PR TITLE
Cleanup code

### PR DESCRIPTION
**Pull request by dhimmel**
Clean up code:
- Adopt [PEP 8](https://www.python.org/dev/peps/pep-0008/) style for imports
- Remove large chunks of quoted code

Return a tuple of (sample_df, fold_change, balanced_permutations, permutations) in analysis.perform_analysis.

Remove log file handling from analysis.py. This file location should be set by the calling program.

Remove `__main__` statements.

### CODE REVIEW

**Comment by dhimmel** [comment]
Note this pull request will overwrite all changes from idrdex/star_api@278ab2d35584d5f6e94aded80a823b3b5f2cf254. If this commit has important changes those should be manually added back.

**Comment by dhimmel** [comment]
This pull request includes major modifications.

The repository now contains a python package that can be installed locally in development mode (see #8). See [`examples/example.ipynb`](https://github.com/dhimmel/starapi/blob/12d136603f3efd8774589ff74b6e05eeaacae5d2/examples/examples.ipynb) for how to operate.

Creating a package will make the repository easier for users to adapt, and will help remove user-specific analyses from the central package.

**Comment by iDrDex** [comment]
@Suor, can you change the master branch of idrdex/star_api to exactly dhimmel/starapi@e171dd2b1d62cd6714e0321bee1e199836f8858d. This commit includes the optimized permutation test and has the repo designed as a module.

**Comment by Suor** [comment]
Merged manually

**Pull request closed without merging**
